# Generated by Django 5.0.7 on 2024-08-18 12:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('pseudo', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('anime', models.CharField(max_length=255)),
                ('texte', models.TextField()),
                ('validate', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Citation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perso_name', models.CharField(max_length=255)),
                ('anime_name', models.CharField(max_length=255)),
                ('url', models.URLField(max_length=500)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Synopsis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500)),
                ('anime', models.CharField(max_length=255)),
                ('texte', models.TextField()),
                ('validate', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Vitesse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speed', models.IntegerField()),
                ('challenge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='citSyn.challenge')),
                ('citation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='citSyn.citation')),
                ('synopsis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='citSyn.synopsis')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
